-- HR Core Enterprise 0002: additive hardening migration.
ALTER TABLE "positions" ADD COLUMN "level" TEXT;
ALTER TABLE "employees" ADD COLUMN "nationality" TEXT;
ALTER TABLE "employees" ADD COLUMN "date_of_birth" TEXT;
ALTER TABLE "employees" ADD COLUMN "gender" TEXT;
ALTER TABLE "employees" ADD COLUMN "address" TEXT;
ALTER TABLE "employees" ADD COLUMN "work_location" TEXT;
ALTER TABLE "employees" ADD COLUMN "contract_type" TEXT;
ALTER TABLE "employees" ADD COLUMN "grade" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_name" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_code" TEXT;
ALTER TABLE "employees" ADD COLUMN "iban" TEXT;
ALTER TABLE "employees" ADD COLUMN "account_number" TEXT;
ALTER TABLE "employees" ADD COLUMN "account_holder" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_status" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_currency" TEXT DEFAULT 'SAR';
ALTER TABLE "employee_assignments" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_assignments" ADD COLUMN "manager_id" INTEGER;
ALTER TABLE "employee_assignments" ADD COLUMN "work_location" TEXT;
ALTER TABLE "transaction_definitions" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "transaction_fields" ADD COLUMN "label_en" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "default_value" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "validation_json" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "visibility" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "editable" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "workflow_steps" ADD COLUMN "actor_type" TEXT NOT NULL DEFAULT 'role';
ALTER TABLE "workflow_steps" ADD COLUMN "actor_user_id" INTEGER;
ALTER TABLE "workflow_steps" ADD COLUMN "department_id" INTEGER;
ALTER TABLE "workflow_steps" ADD COLUMN "condition_json" TEXT;
ALTER TABLE "workflow_steps" ADD COLUMN "actions_json" TEXT;
ALTER TABLE "transactions" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_components" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_compensation" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_compensation" ADD COLUMN "effective_to" TEXT;
ALTER TABLE "payroll_periods" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_periods" ADD COLUMN "approved_at" TEXT;
ALTER TABLE "payroll_periods" ADD COLUMN "locked_at" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_items" ADD COLUMN "employee_status" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "bank_name" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "iban" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "other_deductions" REAL NOT NULL DEFAULT 0;
ALTER TABLE "audit_logs" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "sessions" ADD COLUMN "company_id" INTEGER;
CREATE TABLE IF NOT EXISTS user_roles (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,role_id INTEGER NOT NULL,company_id INTEGER,scope_type TEXT NOT NULL DEFAULT 'company',scope_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_role_company ON user_roles(user_id,role_id,company_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_companies_code ON companies(code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_employees_company_no ON employees(company_id,employee_no);
CREATE INDEX IF NOT EXISTS ix_transactions_company ON transactions(company_id,status);
CREATE INDEX IF NOT EXISTS ix_payroll_period_company ON payroll_periods(company_id,status);
CREATE INDEX IF NOT EXISTS ix_payroll_items_period ON payroll_items(period_id);
CREATE INDEX IF NOT EXISTS ix_audit_company ON audit_logs(company_id,created_at);
