name = "hr-core1"
main = "src/worker.js"
compatibility_date = "2026-09-21"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "hr-core1"
database_id = "5cc62d7a-88b0-4e4f-b25f-d952c1cf783b"
