CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER NOT NULL DEFAULT 0,"name" TEXT NOT NULL,"applied_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "companies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"name_ar" TEXT NOT NULL,"name_en" TEXT,"code" TEXT,"commercial_registration" TEXT,"tax_number" TEXT,"phone" TEXT,"email" TEXT,"address" TEXT,"city" TEXT,"country" TEXT NOT NULL DEFAULT 'Saudi Arabia',"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "departments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"company_id" INTEGER,"parent_id" INTEGER,"code" TEXT NOT NULL,"name_ar" TEXT NOT NULL,"name_en" TEXT,"manager_employee_id" INTEGER,"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "positions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"department_id" INTEGER NOT NULL,"code" TEXT NOT NULL,"title_ar" TEXT NOT NULL,"title_en" TEXT,"grade" TEXT,"approved_headcount" INTEGER NOT NULL DEFAULT 1,"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "vacancies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"position_id" INTEGER NOT NULL,"slot_no" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'open',"employee_id" INTEGER,"opened_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"occupied_at" TEXT,"closed_at" TEXT);
CREATE TABLE IF NOT EXISTS "employees" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"company_id" INTEGER,"employee_no" TEXT NOT NULL,"national_id" TEXT,"name_ar" TEXT NOT NULL,"name_en" TEXT,"email" TEXT,"phone" TEXT,"job_title" TEXT,"department_id" INTEGER,"position_id" INTEGER,"manager_id" INTEGER,"hire_date" TEXT,"employment_status" TEXT NOT NULL DEFAULT 'active',"basic_salary" REAL NOT NULL DEFAULT 0,"housing_allowance" REAL NOT NULL DEFAULT 0,"transport_allowance" REAL NOT NULL DEFAULT 0,"other_allowances" REAL NOT NULL DEFAULT 0,"gosi_enabled" INTEGER NOT NULL DEFAULT 1,"gosi_rate" REAL NOT NULL DEFAULT 9.0,"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "employee_assignments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"employee_id" INTEGER NOT NULL,"department_id" INTEGER,"position_id" INTEGER,"vacancy_id" INTEGER,"start_date" TEXT NOT NULL,"end_date" TEXT,"is_current" INTEGER NOT NULL DEFAULT 1,"reason" TEXT,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "roles" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"code" TEXT NOT NULL UNIQUE,"name_ar" TEXT NOT NULL,"name_en" TEXT,"description" TEXT,"is_system" INTEGER NOT NULL DEFAULT 0,"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "permissions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"code" TEXT NOT NULL UNIQUE,"name_ar" TEXT NOT NULL,"module" TEXT,"scope_type" TEXT NOT NULL DEFAULT 'all',"active" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "role_permissions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"role_id" INTEGER NOT NULL,"permission_id" INTEGER NOT NULL,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"username" TEXT NOT NULL UNIQUE,"password_hash" TEXT NOT NULL,"display_name" TEXT NOT NULL,"email" TEXT,"employee_id" INTEGER,"role_id" INTEGER NOT NULL,"company_id" INTEGER,"active" INTEGER NOT NULL DEFAULT 1,"must_change_password" INTEGER NOT NULL DEFAULT 1,"last_login_at" TEXT,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "sessions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"session_token" TEXT NOT NULL UNIQUE,"user_id" INTEGER NOT NULL,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"expires_at" TEXT NOT NULL,"revoked_at" TEXT);
CREATE TABLE IF NOT EXISTS "transaction_definitions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"code" TEXT NOT NULL UNIQUE,"name_ar" TEXT NOT NULL,"name_en" TEXT,"description" TEXT,"category" TEXT,"active" INTEGER NOT NULL DEFAULT 1,"version" INTEGER NOT NULL DEFAULT 1,"created_by" INTEGER,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "transaction_fields" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"definition_id" INTEGER NOT NULL,"field_key" TEXT NOT NULL,"label_ar" TEXT NOT NULL,"field_type" TEXT NOT NULL DEFAULT 'text',"required" INTEGER NOT NULL DEFAULT 0,"options_json" TEXT,"sort_order" INTEGER NOT NULL DEFAULT 0,"active" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "workflow_definitions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"definition_id" INTEGER NOT NULL,"name_ar" TEXT NOT NULL,"active" INTEGER NOT NULL DEFAULT 1,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "workflow_steps" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"workflow_id" INTEGER NOT NULL,"step_order" INTEGER NOT NULL,"name_ar" TEXT NOT NULL,"role_id" INTEGER,"required_permission" TEXT,"is_final" INTEGER NOT NULL DEFAULT 0,"active" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "transactions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"transaction_no" TEXT NOT NULL UNIQUE,"definition_id" INTEGER NOT NULL,"employee_id" INTEGER,"created_by" INTEGER NOT NULL,"current_step_id" INTEGER,"status" TEXT NOT NULL DEFAULT 'draft',"subject" TEXT,"notes" TEXT,"submitted_at" TEXT,"completed_at" TEXT,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "transaction_values" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"transaction_id" INTEGER NOT NULL,"field_id" INTEGER NOT NULL,"value_text" TEXT,"value_number" REAL,"value_date" TEXT,"value_json" TEXT);
CREATE TABLE IF NOT EXISTS "transaction_history" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"transaction_id" INTEGER NOT NULL,"from_status" TEXT,"to_status" TEXT,"action" TEXT NOT NULL,"comment" TEXT,"actor_user_id" INTEGER,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "payroll_components" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"code" TEXT NOT NULL UNIQUE,"name_ar" TEXT NOT NULL,"type" TEXT NOT NULL,"taxable" INTEGER NOT NULL DEFAULT 0,"active" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "employee_compensation" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"employee_id" INTEGER NOT NULL,"effective_from" TEXT NOT NULL,"basic_salary" REAL NOT NULL DEFAULT 0,"housing_allowance" REAL NOT NULL DEFAULT 0,"transport_allowance" REAL NOT NULL DEFAULT 0,"other_allowances" REAL NOT NULL DEFAULT 0,"gosi_enabled" INTEGER NOT NULL DEFAULT 1,"gosi_rate" REAL NOT NULL DEFAULT 9.0,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "payroll_periods" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"name_ar" TEXT NOT NULL,"period_start" TEXT NOT NULL,"period_end" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'open',"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "payroll_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"period_id" INTEGER NOT NULL,"employee_id" INTEGER NOT NULL,"basic_salary" REAL NOT NULL DEFAULT 0,"housing_allowance" REAL NOT NULL DEFAULT 0,"transport_allowance" REAL NOT NULL DEFAULT 0,"other_allowances" REAL NOT NULL DEFAULT 0,"gosi_base" REAL NOT NULL DEFAULT 0,"gosi_amount" REAL NOT NULL DEFAULT 0,"gross_salary" REAL NOT NULL DEFAULT 0,"net_salary" REAL NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'calculated');
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"user_id" INTEGER,"action" TEXT NOT NULL,"entity_type" TEXT,"entity_id" INTEGER,"details_json" TEXT,"ip" TEXT,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "notifications" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"user_id" INTEGER NOT NULL,"title" TEXT NOT NULL,"body" TEXT,"type" TEXT,"read_at" TEXT,"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "system_settings" ("id" INTEGER PRIMARY KEY AUTOINCREMENT,"setting_key" TEXT NOT NULL UNIQUE,"setting_value" TEXT,"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS ux_employees_employee_no ON employees(employee_no);
CREATE INDEX IF NOT EXISTS ix_employees_department ON employees(department_id);
CREATE INDEX IF NOT EXISTS ix_vacancies_position_status ON vacancies(position_id,status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_role_permission ON role_permissions(role_id,permission_id);
CREATE INDEX IF NOT EXISTS ix_users_role ON users(role_id);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_transactions_definition ON transactions(definition_id);
CREATE INDEX IF NOT EXISTS ix_transactions_employee ON transactions(employee_id);
CREATE INDEX IF NOT EXISTS ix_payroll_items_period ON payroll_items(period_id);

-- HR Core Enterprise 0002: additive hardening migration.
ALTER TABLE "positions" ADD COLUMN "level" TEXT;
ALTER TABLE "employees" ADD COLUMN "nationality" TEXT;
ALTER TABLE "employees" ADD COLUMN "date_of_birth" TEXT;
ALTER TABLE "employees" ADD COLUMN "gender" TEXT;
ALTER TABLE "employees" ADD COLUMN "address" TEXT;
ALTER TABLE "employees" ADD COLUMN "work_location" TEXT;
ALTER TABLE "employees" ADD COLUMN "contract_type" TEXT;
ALTER TABLE "employees" ADD COLUMN "grade" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_name" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_code" TEXT;
ALTER TABLE "employees" ADD COLUMN "iban" TEXT;
ALTER TABLE "employees" ADD COLUMN "account_number" TEXT;
ALTER TABLE "employees" ADD COLUMN "account_holder" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_status" TEXT;
ALTER TABLE "employees" ADD COLUMN "bank_currency" TEXT DEFAULT 'SAR';
ALTER TABLE "employee_assignments" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_assignments" ADD COLUMN "manager_id" INTEGER;
ALTER TABLE "employee_assignments" ADD COLUMN "work_location" TEXT;
ALTER TABLE "transaction_definitions" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "transaction_fields" ADD COLUMN "label_en" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "default_value" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "validation_json" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "visibility" TEXT;
ALTER TABLE "transaction_fields" ADD COLUMN "editable" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "workflow_steps" ADD COLUMN "actor_type" TEXT NOT NULL DEFAULT 'role';
ALTER TABLE "workflow_steps" ADD COLUMN "actor_user_id" INTEGER;
ALTER TABLE "workflow_steps" ADD COLUMN "department_id" INTEGER;
ALTER TABLE "workflow_steps" ADD COLUMN "condition_json" TEXT;
ALTER TABLE "workflow_steps" ADD COLUMN "actions_json" TEXT;
ALTER TABLE "transactions" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_components" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_compensation" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "employee_compensation" ADD COLUMN "effective_to" TEXT;
ALTER TABLE "payroll_periods" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_periods" ADD COLUMN "approved_at" TEXT;
ALTER TABLE "payroll_periods" ADD COLUMN "locked_at" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "payroll_items" ADD COLUMN "employee_status" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "bank_name" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "iban" TEXT;
ALTER TABLE "payroll_items" ADD COLUMN "other_deductions" REAL NOT NULL DEFAULT 0;
ALTER TABLE "audit_logs" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN "company_id" INTEGER;
ALTER TABLE "sessions" ADD COLUMN "company_id" INTEGER;
CREATE TABLE IF NOT EXISTS user_roles (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,role_id INTEGER NOT NULL,company_id INTEGER,scope_type TEXT NOT NULL DEFAULT 'company',scope_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_role_company ON user_roles(user_id,role_id,company_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_companies_code ON companies(code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_employees_company_no ON employees(company_id,employee_no);
CREATE INDEX IF NOT EXISTS ix_transactions_company ON transactions(company_id,status);
CREATE INDEX IF NOT EXISTS ix_payroll_period_company ON payroll_periods(company_id,status);
CREATE INDEX IF NOT EXISTS ix_payroll_items_period ON payroll_items(period_id);
CREATE INDEX IF NOT EXISTS ix_audit_company ON audit_logs(company_id,created_at);
