const REQUIRED = {
  companies:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['name_ar','TEXT NOT NULL'],['name_en','TEXT'],['code','TEXT'],['commercial_registration','TEXT'],['tax_number','TEXT'],['phone','TEXT'],['email','TEXT'],['address','TEXT'],['city','TEXT'],['country',"TEXT NOT NULL DEFAULT 'Saudi Arabia'"],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  departments:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['company_id','INTEGER'],['parent_id','INTEGER'],['code','TEXT NOT NULL'],['name_ar','TEXT NOT NULL'],['name_en','TEXT'],['unit_type',"TEXT NOT NULL DEFAULT 'department'"],['manager_employee_id','INTEGER'],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  positions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['department_id','INTEGER NOT NULL'],['code','TEXT NOT NULL'],['title_ar','TEXT NOT NULL'],['title_en','TEXT'],['grade','TEXT'],['level','TEXT'],['approved_headcount','INTEGER NOT NULL DEFAULT 1'],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  vacancies:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['position_id','INTEGER NOT NULL'],['slot_no','INTEGER NOT NULL'],['status',"TEXT NOT NULL DEFAULT 'open'"],['employee_id','INTEGER'],['opened_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['occupied_at','TEXT'],['closed_at','TEXT']],
  employees:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['company_id','INTEGER'],['employee_no','TEXT NOT NULL'],['national_id','TEXT'],['name_ar','TEXT NOT NULL'],['name_en','TEXT'],['nationality','TEXT'],['date_of_birth','TEXT'],['gender','TEXT'],['email','TEXT'],['phone','TEXT'],['address','TEXT'],['job_title','TEXT'],['department_id','INTEGER'],['position_id','INTEGER'],['manager_id','INTEGER'],['work_location','TEXT'],['contract_type','TEXT'],['grade','TEXT'],['hire_date','TEXT'],['employment_status',"TEXT NOT NULL DEFAULT 'active'"],['basic_salary','REAL NOT NULL DEFAULT 0'],['housing_allowance','REAL NOT NULL DEFAULT 0'],['transport_allowance','REAL NOT NULL DEFAULT 0'],['other_allowances','REAL NOT NULL DEFAULT 0'],['gosi_enabled','INTEGER NOT NULL DEFAULT 1'],['gosi_rate','REAL NOT NULL DEFAULT 9.0'],['bank_name','TEXT'],['bank_code','TEXT'],['iban','TEXT'],['account_number','TEXT'],['account_holder','TEXT'],['bank_status','TEXT'],['bank_currency',"TEXT DEFAULT 'SAR'"],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  employee_assignments:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['employee_id','INTEGER NOT NULL'],['company_id','INTEGER'],['department_id','INTEGER'],['position_id','INTEGER'],['vacancy_id','INTEGER'],['manager_id','INTEGER'],['work_location','TEXT'],['start_date','TEXT NOT NULL'],['end_date','TEXT'],['is_current','INTEGER NOT NULL DEFAULT 1'],['reason','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  roles:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['code','TEXT NOT NULL UNIQUE'],['name_ar','TEXT NOT NULL'],['name_en','TEXT'],['description','TEXT'],['is_system','INTEGER NOT NULL DEFAULT 0'],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  permissions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['code','TEXT NOT NULL UNIQUE'],['name_ar','TEXT NOT NULL'],['module','TEXT'],['scope_type',"TEXT NOT NULL DEFAULT 'all'"],['active','INTEGER NOT NULL DEFAULT 1']],
  role_permissions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['role_id','INTEGER NOT NULL'],['permission_id','INTEGER NOT NULL'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  user_roles:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['user_id','INTEGER NOT NULL'],['role_id','INTEGER NOT NULL'],['company_id','INTEGER'],['scope_type',"TEXT NOT NULL DEFAULT 'company'"],['scope_id','INTEGER'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  users:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['username','TEXT NOT NULL UNIQUE'],['password_hash','TEXT NOT NULL'],['display_name','TEXT NOT NULL'],['email','TEXT'],['employee_id','INTEGER'],['role_id','INTEGER NOT NULL'],['company_id','INTEGER'],['active','INTEGER NOT NULL DEFAULT 1'],['must_change_password','INTEGER NOT NULL DEFAULT 1'],['last_login_at','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  sessions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['session_token','TEXT NOT NULL UNIQUE'],['user_id','INTEGER NOT NULL'],['company_id','INTEGER'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['expires_at','TEXT NOT NULL'],['revoked_at','TEXT']],
  transaction_definitions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['company_id','INTEGER'],['code','TEXT NOT NULL UNIQUE'],['name_ar','TEXT NOT NULL'],['name_en','TEXT'],['description','TEXT'],['category','TEXT'],['active','INTEGER NOT NULL DEFAULT 1'],['version','INTEGER NOT NULL DEFAULT 1'],['created_by','INTEGER'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  transaction_fields:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['definition_id','INTEGER NOT NULL'],['field_key','TEXT NOT NULL'],['label_ar','TEXT NOT NULL'],['label_en','TEXT'],['field_type',"TEXT NOT NULL DEFAULT 'text'"],['required','INTEGER NOT NULL DEFAULT 0'],['default_value','TEXT'],['validation_json','TEXT'],['visibility','TEXT'],['editable','INTEGER NOT NULL DEFAULT 1'],['options_json','TEXT'],['sort_order','INTEGER NOT NULL DEFAULT 0'],['active','INTEGER NOT NULL DEFAULT 1']],
  workflow_definitions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['definition_id','INTEGER NOT NULL'],['name_ar','TEXT NOT NULL'],['active','INTEGER NOT NULL DEFAULT 1'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  workflow_steps:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['workflow_id','INTEGER NOT NULL'],['step_order','INTEGER NOT NULL'],['name_ar','TEXT NOT NULL'],['role_id','INTEGER'],['required_permission','TEXT'],['actor_type',"TEXT NOT NULL DEFAULT 'role'"],['actor_user_id','INTEGER'],['department_id','INTEGER'],['condition_json','TEXT'],['actions_json','TEXT'],['is_final','INTEGER NOT NULL DEFAULT 0'],['active','INTEGER NOT NULL DEFAULT 1']],
  transactions:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['transaction_no','TEXT NOT NULL UNIQUE'],['company_id','INTEGER'],['definition_id','INTEGER NOT NULL'],['employee_id','INTEGER'],['created_by','INTEGER NOT NULL'],['current_step_id','INTEGER'],['status',"TEXT NOT NULL DEFAULT 'draft'"],['subject','TEXT'],['notes','TEXT'],['submitted_at','TEXT'],['completed_at','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  transaction_values:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['transaction_id','INTEGER NOT NULL'],['field_id','INTEGER NOT NULL'],['value_text','TEXT'],['value_number','REAL'],['value_date','TEXT'],['value_json','TEXT']],
  transaction_history:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['transaction_id','INTEGER NOT NULL'],['from_status','TEXT'],['to_status','TEXT'],['action','TEXT NOT NULL'],['comment','TEXT'],['actor_user_id','INTEGER'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  payroll_components:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['company_id','INTEGER'],['code','TEXT NOT NULL UNIQUE'],['name_ar','TEXT NOT NULL'],['type','TEXT NOT NULL'],['taxable','INTEGER NOT NULL DEFAULT 0'],['active','INTEGER NOT NULL DEFAULT 1']],
  employee_compensation:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['employee_id','INTEGER NOT NULL'],['company_id','INTEGER'],['effective_from','TEXT NOT NULL'],['effective_to','TEXT'],['basic_salary','REAL NOT NULL DEFAULT 0'],['housing_allowance','REAL NOT NULL DEFAULT 0'],['transport_allowance','REAL NOT NULL DEFAULT 0'],['other_allowances','REAL NOT NULL DEFAULT 0'],['gosi_enabled','INTEGER NOT NULL DEFAULT 1'],['gosi_rate','REAL NOT NULL DEFAULT 9.0'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  payroll_periods:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['company_id','INTEGER'],['name_ar','TEXT NOT NULL'],['period_start','TEXT NOT NULL'],['period_end','TEXT NOT NULL'],['status',"TEXT NOT NULL DEFAULT 'open'"],['approved_at','TEXT'],['locked_at','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  payroll_items:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['period_id','INTEGER NOT NULL'],['company_id','INTEGER'],['employee_id','INTEGER NOT NULL'],['employee_status','TEXT'],['bank_name','TEXT'],['iban','TEXT'],['basic_salary','REAL NOT NULL DEFAULT 0'],['housing_allowance','REAL NOT NULL DEFAULT 0'],['transport_allowance','REAL NOT NULL DEFAULT 0'],['other_allowances','REAL NOT NULL DEFAULT 0'],['other_deductions','REAL NOT NULL DEFAULT 0'],['gosi_base','REAL NOT NULL DEFAULT 0'],['gosi_amount','REAL NOT NULL DEFAULT 0'],['gross_salary','REAL NOT NULL DEFAULT 0'],['net_salary','REAL NOT NULL DEFAULT 0'],['status',"TEXT NOT NULL DEFAULT 'calculated'"]],
  audit_logs:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['user_id','INTEGER'],['company_id','INTEGER'],['action','TEXT NOT NULL'],['entity_type','TEXT'],['entity_id','INTEGER'],['details_json','TEXT'],['ip','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  notifications:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['user_id','INTEGER NOT NULL'],['company_id','INTEGER'],['title','TEXT NOT NULL'],['body','TEXT'],['type','TEXT'],['read_at','TEXT'],['created_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  system_settings:[['id','INTEGER PRIMARY KEY AUTOINCREMENT'],['setting_key','TEXT NOT NULL UNIQUE'],['setting_value','TEXT'],['updated_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  schema_migrations:[['version','INTEGER NOT NULL DEFAULT 0'],['name','TEXT NOT NULL'],['applied_at',"TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP"]]
};
const perms=[
['dashboard.view','لوحة التحكم','dashboard','all'],['employees.view','عرض الموظفين','employees','company'],['employees.create','إنشاء موظف','employees','company'],['employees.edit','تعديل موظف','employees','company'],['employees.delete','حذف موظف','employees','company'],['employees.bank.view','عرض البيانات البنكية','employees','company'],['employees.salary.view','عرض الراتب','employees','company'],['employees.create_user','إنشاء مستخدم للموظف','users','company'],
['organization.view','عرض الهيكل التنظيمي','organization','company'],['organization.manage','إدارة الهيكل التنظيمي','organization','company'],['positions.manage','إدارة الوظائف','organization','company'],['vacancies.manage','إدارة الشواغر','organization','company'],
['transactions.view','عرض المعاملات','transactions','company'],['transactions.create','إنشاء معاملة','transactions','self'],['transactions.edit','تعديل معاملة','transactions','self'],['transactions.approve','اعتماد المعاملات','transactions','managed'],['transactions.reject','رفض المعاملات','transactions','managed'],['transactions.return','إعادة المعاملة','transactions','managed'],['transactions.complete','إكمال المعاملة','transactions','managed'],['transactions.builder','منشئ المعاملات','transactions','company'],
['payroll.view','عرض الرواتب','payroll','company'],['payroll.calculate','إنشاء المسير واحتسابه','payroll','company'],['payroll.approve','اعتماد المسير','payroll','company'],['payroll.lock','إقفال المسير','payroll','company'],['payroll.export','تصدير المسير','payroll','company'],['payroll.manage','إدارة إعدادات الرواتب','payroll','company'],
['reports.view','عرض التقارير','reports','company'],['reports.export','تصدير التقارير','reports','company'],['roles.view','عرض الأدوار','security','company'],['roles.manage','إدارة الأدوار والصلاحيات','security','company'],['users.view','عرض المستخدمين','security','company'],['users.manage','إدارة المستخدمين','security','company'],['company.manage','إدارة الشركات','security','global'],['audit.view','عرض سجل العمليات','security','global'],['database.health','فحص النظام','security','global'],['settings.manage','إدارة الإعدادات','security','global']
];
const rolePerms={
super_admin:perms.map(x=>x[0]),
hr:['dashboard.view','employees.view','employees.create','employees.edit','employees.bank.view','employees.salary.view','employees.create_user','organization.view','organization.manage','positions.manage','vacancies.manage','transactions.view','transactions.create','transactions.edit','transactions.approve','transactions.reject','transactions.return','transactions.complete','transactions.builder','payroll.view','payroll.calculate','payroll.approve','payroll.export','reports.view','reports.export','roles.view','users.view','users.manage','audit.view'],
manager:['dashboard.view','employees.view','employees.edit','organization.view','transactions.view','transactions.approve','transactions.reject','transactions.return','transactions.complete','reports.view'],
employee:['dashboard.view','employees.view','transactions.view','transactions.create','transactions.edit','payroll.view']
};
async function hasTable(db,t){return !!await db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`).bind(t).first()}
async function ensureTable(db,name,cols){
  if(!await hasTable(db,name)){await db.prepare(`CREATE TABLE IF NOT EXISTS "${name}" (${cols.map(([n,d])=>`"${n}" ${d}`).join(',')})`).run();return}
  const info=await db.prepare(`PRAGMA table_info("${name}")`).all();const have=new Set((info.results||[]).map(x=>x.name));
  for(const [n,d] of cols) if(!have.has(n) && !/PRIMARY KEY/.test(d)) {try{await db.prepare(`ALTER TABLE "${name}" ADD COLUMN "${n}" ${d}`).run()}catch{}}
}
export async function ensureSchema(env){
 const db=env.DB;
 for(const [n,c] of Object.entries(REQUIRED)) await ensureTable(db,n,c);
 const indexes=[
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_companies_code ON companies(code)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_employees_company_no ON employees(company_id,employee_no)`,
  `CREATE INDEX IF NOT EXISTS ix_departments_company ON departments(company_id)`,
  `CREATE INDEX IF NOT EXISTS ix_positions_department ON positions(department_id)`,
  `CREATE INDEX IF NOT EXISTS ix_vacancies_position_status ON vacancies(position_id,status)`,
  `CREATE INDEX IF NOT EXISTS ix_assignments_employee_current ON employee_assignments(employee_id,is_current)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_role_permission ON role_permissions(role_id,permission_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ux_user_role_company ON user_roles(user_id,role_id,company_id)`,
  `CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions(user_id)`,
  `CREATE INDEX IF NOT EXISTS ix_transactions_company ON transactions(company_id,status)`,
  `CREATE INDEX IF NOT EXISTS ix_payroll_period_company ON payroll_periods(company_id,status)`,
  `CREATE INDEX IF NOT EXISTS ix_payroll_items_period ON payroll_items(period_id)`,
  `CREATE INDEX IF NOT EXISTS ix_audit_company ON audit_logs(company_id,created_at)`
 ];
 for(const q of indexes){try{await db.prepare(q).run()}catch{}}
 await seed(db);
 await db.prepare(`INSERT OR IGNORE INTO schema_migrations(version,name) VALUES(3,'performance_organization_transactions')`).run();
}
async function seed(db){
 for(const [code,name_ar,module,scope_type] of perms) await db.prepare(`INSERT OR IGNORE INTO permissions(code,name_ar,module,scope_type) VALUES(?,?,?,?)`).bind(code,name_ar,module,scope_type).run();
 for(const [code,name_ar] of [['super_admin','مدير النظام'],['hr','مدير موارد بشرية'],['manager','مدير مباشر'],['employee','موظف']]) await db.prepare(`INSERT OR IGNORE INTO roles(code,name_ar,name_en,is_system) VALUES(?,?,?,1)`).bind(code,name_ar,code).run();
 for(const [rc,ps] of Object.entries(rolePerms)){const role=await db.prepare(`SELECT id FROM roles WHERE code=?`).bind(rc).first();for(const p of ps){const perm=await db.prepare(`SELECT id FROM permissions WHERE code=?`).bind(p).first();if(role&&perm)await db.prepare(`INSERT OR IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)`).bind(role.id,perm.id).run()}}
 const c=await db.prepare(`SELECT id FROM companies WHERE code='ELITE' LIMIT 1`).first();
 if(!c) await db.prepare(`INSERT INTO companies(name_ar,name_en,code,city,country,active) VALUES('شركة النخبة للتجارة','Elite Trading Company','ELITE','الرياض','Saudi Arabia',1)`).run();
 const sc=await db.prepare(`SELECT id FROM companies WHERE code='SYSTEM' LIMIT 1`).first(); if(!sc) await db.prepare(`INSERT INTO companies(name_ar,name_en,code,active) VALUES('منصة HR Core Enterprise','HR Core Enterprise','SYSTEM',1)`).run();
 const role=await db.prepare(`SELECT id FROM roles WHERE code='super_admin'`).first(); const admin=await db.prepare(`SELECT id FROM users WHERE username='admin'`).first();
 if(!admin) await db.prepare(`INSERT INTO users(username,password_hash,display_name,role_id,company_id,active,must_change_password) VALUES('admin','pbkdf2$100000$YWRtaW4tc2FsdC0yMDI2$38FPEssFOEsudeS7rQL4gfovCum_Qzrhf7H6WKLwCe0','مدير النظام',?,NULL,1,1)`).bind(role.id).run();
 await db.prepare(`INSERT OR IGNORE INTO payroll_components(code,name_ar,type,taxable) VALUES('BASIC','الراتب الأساسي','earning',1),('HOUSING','بدل السكن','earning',1),('TRANSPORT','بدل النقل','earning',1),('OTHER','بدلات أخرى','earning',1),('GOSI','التأمينات الاجتماعية','deduction',0)`).run();
}
export async function schemaHealth(db){const tables=await db.prepare(`SELECT name FROM sqlite_master WHERE type='table' ORDER BY name`).all();return {tables:(tables.results||[]).map(x=>x.name),version:await db.prepare(`SELECT COALESCE(MAX(version),0) v FROM schema_migrations`).first().then(x=>x.v)}}
